import { Farmer } from '@/components/FarmerCard';
import { Product, GrowthStage } from '@/components/ProductCard';
import { Order, TrackingStep, OrderStatus } from '@/components/OrderTracking';
import { Campaign, CrowdfundTier } from '@/components/CrowdfundCard';
import { CustomerProfile, FarmerProfile } from '@/components/ProfileSection';

// Mock Farmers
export const mockFarmers: Farmer[] = [
  {
    id: '1',
    name: 'John Peterson',
    farmName: 'Green Valley Farm',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    coverImage: 'https://images.pexels.com/photos/2132171/pexels-photo-2132171.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Sonoma County, CA',
    distance: 2.5,
    rating: 4.9,
    reviewCount: 156,
    products: 24,
    specialties: ['Lettuce', 'Tomatoes', 'Herbs', 'Microgreens'],
    isOrganic: true,
    isVerified: true,
    totalSales: 1250,
    joinedDate: 'March 2023',
  },
  {
    id: '2',
    name: 'Maria Santos',
    farmName: 'Sunny Acres',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150',
    coverImage: 'https://images.pexels.com/photos/1382102/pexels-photo-1382102.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Napa Valley, CA',
    distance: 5.2,
    rating: 4.8,
    reviewCount: 98,
    products: 18,
    specialties: ['Strawberries', 'Berries', 'Stone Fruits'],
    isOrganic: true,
    isVerified: true,
    totalSales: 890,
    joinedDate: 'June 2023',
  },
  {
    id: '3',
    name: 'Robert Chen',
    farmName: 'Heritage Fields',
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150',
    coverImage: 'https://images.pexels.com/photos/1084540/pexels-photo-1084540.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Marin County, CA',
    distance: 8.1,
    rating: 4.7,
    reviewCount: 72,
    products: 32,
    specialties: ['Root Vegetables', 'Squash', 'Potatoes', 'Garlic'],
    isOrganic: false,
    isVerified: true,
    totalSales: 650,
    joinedDate: 'January 2024',
  },
  {
    id: '4',
    name: 'Emily Wilson',
    farmName: 'Meadow Brook Farm',
    avatar: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=150',
    coverImage: 'https://images.pexels.com/photos/1459339/pexels-photo-1459339.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Petaluma, CA',
    distance: 12.3,
    rating: 4.9,
    reviewCount: 203,
    products: 15,
    specialties: ['Eggs', 'Honey', 'Dairy'],
    isOrganic: true,
    isVerified: true,
    totalSales: 1800,
    joinedDate: 'August 2022',
  },
  {
    id: '5',
    name: 'James Rodriguez',
    farmName: 'Sunrise Orchards',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
    coverImage: 'https://images.pexels.com/photos/1458694/pexels-photo-1458694.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Santa Rosa, CA',
    distance: 15.7,
    rating: 4.6,
    reviewCount: 45,
    products: 12,
    specialties: ['Apples', 'Pears', 'Citrus'],
    isOrganic: false,
    isVerified: false,
    totalSales: 320,
    joinedDate: 'November 2024',
  },
  {
    id: '6',
    name: 'Sarah Miller',
    farmName: 'Riverside Gardens',
    avatar: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=150',
    coverImage: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Healdsburg, CA',
    distance: 18.2,
    rating: 4.8,
    reviewCount: 128,
    products: 28,
    specialties: ['Peppers', 'Cucumbers', 'Zucchini', 'Eggplant'],
    isOrganic: true,
    isVerified: true,
    totalSales: 980,
    joinedDate: 'April 2023',
  },
];

// Mock Products
export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Organic Heirloom Tomatoes',
    image: 'https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: 8,
    currency: 'USDC',
    unit: 'lb',
    farmerId: '1',
    farmerName: 'John Peterson',
    farmName: 'Green Valley Farm',
    farmerAvatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    distance: 2.5,
    isOrganic: true,
    category: 'Vegetables',
    growthStage: 'ready',
    stock: 45,
    rating: 4.9,
  },
  {
    id: 'p2',
    name: 'Fresh Strawberries',
    image: 'https://images.pexels.com/photos/46174/strawberries-berries-fruit-freshness-46174.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: 12,
    currency: 'USDC',
    unit: 'basket',
    farmerId: '2',
    farmerName: 'Maria Santos',
    farmName: 'Sunny Acres',
    farmerAvatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150',
    distance: 5.2,
    isOrganic: true,
    category: 'Fruits',
    growthStage: 'harvest',
    harvestDate: 'Feb 25',
    stock: 20,
    rating: 4.8,
  },
  {
    id: 'p3',
    name: 'Rainbow Carrots',
    image: 'https://images.pexels.com/photos/3650647/pexels-photo-3650647.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: 5,
    currency: 'USDC',
    unit: 'bunch',
    farmerId: '3',
    farmerName: 'Robert Chen',
    farmName: 'Heritage Fields',
    farmerAvatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150',
    distance: 8.1,
    isOrganic: false,
    category: 'Vegetables',
    growthStage: 'maturing',
    harvestDate: 'Mar 5',
    stock: 0,
    rating: 4.7,
  },
  {
    id: 'p4',
    name: 'Farm Fresh Eggs',
    image: 'https://images.pexels.com/photos/162712/egg-white-food-protein-162712.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: 0.15,
    currency: 'SOL',
    unit: 'dozen',
    farmerId: '4',
    farmerName: 'Emily Wilson',
    farmName: 'Meadow Brook Farm',
    farmerAvatar: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=150',
    distance: 12.3,
    isOrganic: true,
    category: 'Dairy & Eggs',
    growthStage: 'ready',
    stock: 100,
    rating: 4.9,
  },
  {
    id: 'p5',
    name: 'Mixed Salad Greens',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: 6,
    currency: 'USDC',
    unit: 'bag',
    farmerId: '1',
    farmerName: 'John Peterson',
    farmName: 'Green Valley Farm',
    farmerAvatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    distance: 2.5,
    isOrganic: true,
    category: 'Vegetables',
    growthStage: 'growing',
    harvestDate: 'Mar 10',
    stock: 0,
    rating: 4.8,
  },
  {
    id: 'p6',
    name: 'Raw Wildflower Honey',
    image: 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: 18,
    currency: 'USDC',
    unit: 'jar',
    farmerId: '4',
    farmerName: 'Emily Wilson',
    farmName: 'Meadow Brook Farm',
    farmerAvatar: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=150',
    distance: 12.3,
    isOrganic: true,
    category: 'Specialty',
    growthStage: 'ready',
    stock: 35,
    rating: 5.0,
  },
  {
    id: 'p7',
    name: 'Organic Zucchini',
    image: 'https://images.pexels.com/photos/128420/pexels-photo-128420.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: 4,
    currency: 'USDC',
    unit: 'lb',
    farmerId: '6',
    farmerName: 'Sarah Miller',
    farmName: 'Riverside Gardens',
    farmerAvatar: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=150',
    distance: 18.2,
    isOrganic: true,
    category: 'Vegetables',
    growthStage: 'seed',
    harvestDate: 'Apr 1',
    stock: 0,
    rating: 4.7,
  },
  {
    id: 'p8',
    name: 'Honeycrisp Apples',
    image: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=600',
    price: 7,
    currency: 'USDC',
    unit: 'lb',
    farmerId: '5',
    farmerName: 'James Rodriguez',
    farmName: 'Sunrise Orchards',
    farmerAvatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
    distance: 15.7,
    isOrganic: false,
    category: 'Fruits',
    growthStage: 'ready',
    stock: 60,
    rating: 4.6,
  },
];

// Mock Orders
const createTrackingSteps = (currentStatus: OrderStatus): TrackingStep[] => {
  const statuses: { status: OrderStatus; title: string; description: string }[] = [
    { status: 'seed', title: 'Planted', description: 'Seeds have been planted in fertile soil' },
    { status: 'growing', title: 'Growing', description: 'Plants are thriving with proper care' },
    { status: 'harvesting', title: 'Harvesting', description: 'Fresh produce being carefully harvested' },
    { status: 'processing', title: 'Processing', description: 'Cleaning, sorting, and packaging' },
    { status: 'shipping', title: 'On the Way', description: 'Your order is being delivered' },
    { status: 'delivered', title: 'Delivered', description: 'Enjoy your fresh farm produce!' },
  ];

  const currentIndex = statuses.findIndex(s => s.status === currentStatus);

  return statuses.map((step, index) => ({
    ...step,
    isCompleted: index < currentIndex,
    isCurrent: index === currentIndex,
    timestamp: index <= currentIndex ? `Feb ${15 + index}, 2026 - ${9 + index}:00 AM` : undefined,
  }));
};

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    productName: 'Organic Heirloom Tomatoes',
    productImage: 'https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=600',
    farmName: 'Green Valley Farm',
    farmerName: 'John Peterson',
    quantity: 5,
    unit: 'lbs',
    totalPrice: 40,
    currency: 'USDC',
    trackingSteps: createTrackingSteps('shipping'),
    estimatedDelivery: 'Feb 22, 2026',
    txHash: '5KQq...xR7m',
  },
  {
    id: 'ORD-002',
    productName: 'Fresh Strawberries',
    productImage: 'https://images.pexels.com/photos/46174/strawberries-berries-fruit-freshness-46174.jpeg?auto=compress&cs=tinysrgb&w=600',
    farmName: 'Sunny Acres',
    farmerName: 'Maria Santos',
    quantity: 3,
    unit: 'baskets',
    totalPrice: 36,
    currency: 'USDC',
    trackingSteps: createTrackingSteps('harvesting'),
    estimatedDelivery: 'Feb 28, 2026',
    txHash: '8Hkp...mN2v',
  },
  {
    id: 'ORD-003',
    productName: 'Farm Fresh Eggs',
    productImage: 'https://images.pexels.com/photos/162712/egg-white-food-protein-162712.jpeg?auto=compress&cs=tinysrgb&w=600',
    farmName: 'Meadow Brook Farm',
    farmerName: 'Emily Wilson',
    quantity: 2,
    unit: 'dozens',
    totalPrice: 0.3,
    currency: 'SOL',
    trackingSteps: createTrackingSteps('delivered'),
    estimatedDelivery: 'Feb 18, 2026',
    txHash: '2Lpq...sT5w',
  },
];

// Mock Campaigns
export const mockCampaigns: Campaign[] = [
  {
    id: 'c1',
    title: 'Expand Greenhouse for Year-Round Tomatoes',
    farmName: 'Green Valley Farm',
    farmerName: 'John Peterson',
    farmerAvatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    coverImage: 'https://images.pexels.com/photos/2132171/pexels-photo-2132171.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Help us build a new greenhouse to grow organic tomatoes year-round. Backers get first access to fresh produce at discounted prices.',
    goal: 5000,
    raised: 3250,
    currency: 'USDC',
    backers: 47,
    daysLeft: 18,
    category: 'Infrastructure',
    updates: 5,
    tiers: [
      {
        id: 't1',
        name: 'Seed Supporter',
        amount: 25,
        currency: 'USDC',
        description: 'Early supporter tier',
        benefits: ['10% off first order', 'Farm newsletter', 'Digital thank you card'],
        backers: 28,
      },
      {
        id: 't2',
        name: 'Growing Partner',
        amount: 100,
        currency: 'USDC',
        description: 'Perfect for produce lovers',
        benefits: ['20% off all orders for 6 months', 'Monthly farm box delivery', 'Name on supporter wall', 'Early harvest notifications'],
        backers: 15,
        limitedTo: 25,
      },
      {
        id: 't3',
        name: 'Harvest Hero',
        amount: 500,
        currency: 'USDC',
        description: 'VIP farm experience',
        benefits: ['30% lifetime discount', 'Free monthly delivery', 'Private farm tour', 'Hands-on farming workshop', 'Annual harvest celebration invite'],
        backers: 4,
        limitedTo: 10,
      },
    ],
  },
  {
    id: 'c2',
    title: 'New Berry Varieties & Organic Certification',
    farmName: 'Sunny Acres',
    farmerName: 'Maria Santos',
    farmerAvatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150',
    coverImage: 'https://images.pexels.com/photos/1382102/pexels-photo-1382102.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'We\'re introducing new berry varieties and getting organic certification. Support us and enjoy exclusive access to rare berries!',
    goal: 3000,
    raised: 1800,
    currency: 'USDC',
    backers: 32,
    daysLeft: 25,
    category: 'Expansion',
    updates: 3,
    tiers: [
      {
        id: 't1',
        name: 'Berry Buddy',
        amount: 20,
        currency: 'USDC',
        description: 'Support our berry mission',
        benefits: ['First taste of new varieties', 'Berry recipe e-book', 'Thank you postcard'],
        backers: 20,
      },
      {
        id: 't2',
        name: 'Berry Enthusiast',
        amount: 75,
        currency: 'USDC',
        description: 'For serious berry lovers',
        benefits: ['Monthly berry subscription for 3 months', '15% off all purchases', 'Name a berry row after you'],
        backers: 10,
        limitedTo: 20,
      },
      {
        id: 't3',
        name: 'Berry VIP',
        amount: 250,
        currency: 'USDC',
        description: 'Ultimate berry experience',
        benefits: ['Year of monthly berry boxes', '25% lifetime discount', 'Berry picking day pass', 'Farm dinner experience'],
        backers: 2,
        limitedTo: 5,
      },
    ],
  },
  {
    id: 'c3',
    title: 'Solar-Powered Irrigation System',
    farmName: 'Heritage Fields',
    farmerName: 'Robert Chen',
    farmerAvatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150',
    coverImage: 'https://images.pexels.com/photos/1084540/pexels-photo-1084540.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Going green with solar-powered irrigation! Help us reduce our carbon footprint while improving crop yields.',
    goal: 8000,
    raised: 2400,
    currency: 'USDC',
    backers: 28,
    daysLeft: 35,
    category: 'Sustainability',
    updates: 2,
    tiers: [
      {
        id: 't1',
        name: 'Green Supporter',
        amount: 50,
        currency: 'USDC',
        description: 'Support sustainable farming',
        benefits: ['Sustainability impact report', '10% off orders', 'Digital certificate'],
        backers: 18,
      },
      {
        id: 't2',
        name: 'Eco Champion',
        amount: 200,
        currency: 'USDC',
        description: 'Champion level support',
        benefits: ['20% off for 1 year', 'Quarterly farm boxes', 'Solar panel dedication', 'Farm tour'],
        backers: 8,
        limitedTo: 15,
      },
      {
        id: 't3',
        name: 'Sustainability Partner',
        amount: 1000,
        currency: 'USDC',
        description: 'Partner-level investment',
        benefits: ['30% lifetime discount', 'Monthly premium boxes', 'Plaque on solar installation', 'Annual VIP dinner', 'Business partnership options'],
        backers: 2,
        limitedTo: 5,
      },
    ],
  },
];

// Mock Customer Profile
export const mockCustomerProfile: CustomerProfile = {
  id: 'cust1',
  name: 'Alex Thompson',
  avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150',
  email: 'alex@example.com',
  location: 'San Francisco, CA',
  coordinates: { lat: 37.7749, lng: -122.4194 },
  joinedDate: 'January 2024',
  walletAddress: '9PJ8I3sPnKDLMVh2P6YwZk5J1234567890abcdef3555',
  totalOrders: 24,
  totalSpent: 856,
  currency: 'USDC',
  favoriteFarms: 5,
  investedCampaigns: 3,
  investmentTotal: 175,
  level: 'Gold',
  levelProgress: 72,
};

// Mock Farmer Profile
export const mockFarmerProfile: FarmerProfile = {
  id: '1',
  name: 'John Peterson',
  farmName: 'Green Valley Farm',
  avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
  coverImage: 'https://images.pexels.com/photos/2132171/pexels-photo-2132171.jpeg?auto=compress&cs=tinysrgb&w=800',
  bio: 'Third-generation farmer passionate about sustainable agriculture. Growing organic produce using regenerative farming practices since 2018.',
  email: 'john@greenvalleyfarm.com',
  location: 'Sonoma County, CA',
  coordinates: { lat: 38.2919, lng: -122.4580 },
  joinedDate: 'March 2023',
  walletAddress: '7Hkq2wPnKDLMVh2P6YwZk5J1234567890abcdef8899',
  isOrganic: true,
  isVerified: true,
  rating: 4.9,
  reviewCount: 156,
  totalProducts: 24,
  totalSales: 1250,
  totalRevenue: 45000,
  currency: 'USDC',
  followers: 328,
  activeCampaigns: 1,
  specialties: ['Lettuce', 'Tomatoes', 'Herbs', 'Microgreens'],
  certifications: ['USDA Organic', 'Non-GMO Project', 'Regenerative Organic'],
};
